---
title: "Maps"
output: html_document
date: "2025-11-15"
---

```{r, include = F}
library(gifski)
# for loading our data
library(countries)
library(raster)
library(readr)
library(readxl)
library(sf)
# for datasets
library(maps)
library(spData)
# for plotting
library(grid)
library(tmap)
library(viridis)
library(tidyverse)
```

--- 

Learn about 'shapefiles': https://r-graph-gallery.com/168-load-a-shape-file-into-r.html

--- 

```{r}
World <- tmap::World
```

```{r, include = F}
data <- read_csv("data/economics_and_education_dataset_CSV.csv") %>% 
  mutate(iso_a3 = country_name(index_code))
```

```{r, include = F}
d2000s <- data %>% filter(time > 2001, time <= 2009) %>% 
  summarise(mmri = mean(mortality_rate_infant),
            unemployment = mean(unemployment), .by = c("time", "iso_a3"))
d2010s <- data %>% filter(time > 2010, time <= 2020) %>% 
  summarise(mmri = mean(mortality_rate_infant),
            unemployment = mean(unemployment), .by = c("time", "iso_a3"))
```

```{r, include = F}
joint2000 <- World %>% left_join(d2000s, by = "iso_a3") %>% 
  #filter(continent == "Europe") %>% 
  group_by(iso_a3) %>% slice_sample(n = 1) %>% 
  na.omit()
```

```{r, include = F}
joint2010 <- World %>% left_join(d2010s, by = "iso_a3") %>% 
  #filter(continent == "Europe") %>% 
  group_by(iso_a3) %>% slice_sample(n = 1) %>%  
  na.omit()
```

```{r}
tm_shape() + 
  tm_polygons() + 
  tm_compass()
```

Exercise: plot `mmri` for North and South America

```{r}

```

```{r}

```

---

Exercise: make maps with the 'World' shapefile, and its built-in metrics e.g. HPI, pop.

```{r}

```

```{r}

```

```{r}

```

---

